e-learning platform/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/saml_login'

  devise_for :users, controllers: { sessions: 'sessions'}
  resources :users
  devise_for :admins, controllers: {
      sessions: 'admins/sessions', registrations: 'admins/registrations'
  }

  namespace :api do
    namespace :v1 do
      get 'users/create'
      get 'users/show'

      get 'courses/index'
      post 'courses/show'

      post 'quiz/show'
      post 'quiz/create'

      post 'contents/show'
      post 'contents/create'

      post 'authorizations/user_saml_authorization'
      post 'authorizations/authorize_user_by_ip_address', 'authorizations#authorize_user_by_ip_address'
    end
  end

  resources :content_types
  resources :sessions

  resources :quizzes do
    get :user_quiz_completion_graph, on: :collection
  end
  resources :contents do
    post :set_position, on: :collection
  end
  resources :courses

  get '/saml/auth' => 'saml_idp#new'
  post '/saml/auth' => 'saml_idp#create'

  root "courses#index"
end

e-learning platform/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
end

e-learning platform/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  has_many :user_question_answers
  has_many :users, :through => :user_question_answers
end

e-learning platform/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

e-learning platform/app/models/content.rb
class Content < ApplicationRecord
  mount_uploader :file, FileUploader
  process_in_background :file

  has_many :course_content_completions
  has_many :user, :through => :course_content_completions

  belongs_to :content_type
  #belongs_to :quiz
  belongs_to :course, optional: true
  acts_as_list scope: :course
end

e-learning platform/app/models/content_type.rb
class ContentType < ApplicationRecord
  has_many :contents
end

e-learning platform/app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :picture, FileUploader
  mount_uploader :file, FileUploader
  process_in_background :file

  has_many :contents
  accepts_nested_attributes_for :contents, reject_if: :all_blank, allow_destroy: true

  belongs_to :quiz, optional: true
  accepts_nested_attributes_for :quiz, reject_if: :all_blank, allow_destroy: true

  has_many :course_enrollments
  has_many :users, :through => :course_enrollments
end

e-learning platform/app/models/course_enrollment.rb
class CourseEnrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

e-learning platform/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz

  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

e-learning platform/app/models/quiz.rb
class Quiz < ApplicationRecord
  has_one :course

  has_many :questions
  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true

  has_many :course_quiz_completions
  has_many :user, :through => :course_quiz_completions
end

e-learning platform/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

  has_many :course_enrollments
  has_many :courses, :through => :course_enrollments

  has_many :course_content_completions
  has_many :contents, :through => :course_content_completions

  has_many :course_quiz_completions
  has_many :quizzes, :through => :course_quiz_completions

  has_many :user_question_answers
  has_many :answers, :through => :user_question_answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :saml_authenticatable, :trackable

  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable

  before_create :generate_auth_token

  def self.create_user_without_password(params)
    self.create(params)
  end

  def regenerate_auth_token!
    generate_auth_token
    self.auth_token_ip = nil
    save
  end

  protected

  def password_required?
    false
  end

  def generate_auth_token
    loop do
      self.auth_token = Devise.friendly_token
      break unless User.exists?(auth_token: auth_token)
    end
  end
end

e-learning platform/app/models/user_question_answer.rb
class UserQuestionAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

e-learning platform/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:edit, :update, :destroy, :user_quiz_completion_graph]
  skip_before_action :authenticate_admin!, only: [:user_quiz_completion_graph]

  # GET /quizzes
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  def create
    @quiz = Quiz.new(quiz_params)

    if @quiz.save
      redirect_to @quiz, notice: 'Quiz was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /quizzes/1
  def update
    if @quiz.update(quiz_params)
      redirect_to @quiz, notice: 'Quiz was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /quizzes/1
  def destroy
    @quiz.destroy
    redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_quiz
    @quiz = Quiz.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def quiz_params
    params.require(:quiz).permit(:points_to_pass)
  end
end

e-learning platform/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_admin!

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end
end

e-learning platform/app/helpers/application_helper.rb
module ApplicationHelper
end

e-learning platform/app/helpers/content_types_helper.rb
module ContentTypesHelper
end

e-learning platform/app/helpers/contents_helper.rb
module ContentsHelper
end

e-learning platform/app/helpers/courses_helper.rb
module CoursesHelper
end

e-learning platform/app/helpers/quiz_helper.rb
module QuizHelper
end

e-learning platform/app/helpers/quizzes_helper.rb
module QuizzesHelper
end

e-learning platform/app/helpers/saml_idp_helper.rb
module SamlIdpHelper
end

e-learning platform/app/helpers/sessions_helper.rb
module SessionsHelper
end

e-learning platform/app/helpers/users_helper.rb
module UsersHelper
end

e-learning platform/app/views/quizzes/_form.html.erb
<%= simple_form_for(@quiz) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :points_to_pass %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

e-learning platform/app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

e-learning platform/app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Points to pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.points_to_pass %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

e-learning platform/app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

e-learning platform/app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Points to pass:</strong>
  <%= @quiz.points_to_pass %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>

e-learning platform/app/views/quizzes/user_quiz_completion_graph.erb
<style>
    canvas {
      font-size: 18pt;
    }

     .border-content {
       border: 1px solid #3f63f9 !important;
       border-radius: 16px;
       margin-top: 15px;
     }

    .border-margin {
      margin: 10px;
    }

    .nested-fields {
      margin-top: 25px;
    }

    .border-color {
      border-color: #7e81f9!important;
    }

</style>

  <%= pie_chart  CourseQuizCompletion.where(quiz_id: @quiz.id).order('points DESC').includes(:user).map {|quiz| [quiz.user.first_name+" "+quiz.user.last_name,quiz.points]}.first(5), max: @quiz.questions.count,
      id: 'pie', height: "500px", library: { legend: {position: "left", textStyle: {fontSize: "20px", textColor: 'black'}}} %>
<div class="row">
<% @quiz.questions.each do |question| %>
      <div class="col-md-6">
<div class="border-content">
  <div class="border-margin">
    <div class="container-fluid">
      <strong>Question:</strong>
      <p><%= question.title %></p>
      <hr>
      <strong>Correct answer:</strong>
              <div class="border-content border-color">
                <div class="border-margin">
                  <p><%= question.answers.find_by(correct: true).title %></p>
                  <strong><%= "Correct" %></strong>
                </div>
      </div>
    </div>
  </div>
</div>
      </div>
<% end %>
</div>