fundings_app/config/routes.rb
Rails.application.routes.draw do

  get 'offers/show'

  get 'offers/index'

  namespace :api do
  namespace :v1 do
      post 'favorites/create'
      post 'favorites/show'
      post 'favorites/destroy'
      post 'users/show'
      post 'users/create'
      post 'users/update'
      post 'users/destroy'
      post 'sessions/create'
      post 'sessions/destroy'
      post 'fundings/show'
      post 'fundings/index'
      post 'task/show'
      post 'task/create'
      post 'task/update'
      post 'offers/create'

      post 'notifications/set_flag'
      resource :filter, only: [:show, :create]
      resource :sms_confirmation, only: :create

      namespace :mobile do
        post 'ios_push_notifications/add_push_id_to_user'
        post 'ios_push_notifications/set_flag'
        post 'favorites/create'
        post 'favorites/show'
        post 'favorites/destroy'
        post 'users/show'
        post 'users/create'
        post 'users/update'
        post 'users/destroy'
        post 'android_sessions/create'
        post 'android_sessions/destroy'
        post 'ios_sessions/create'
        post 'ios_sessions/destroy'
        post 'fundings/show'
        post 'fundings/index'
        post 'android_push_notifications/set_flag'
        post 'android_push_notifications/add_push_id_to_user'

        resource :filter, only: [:show, :create]

        resources :users do
          post :check_oib, on: :collection
          post :reset_password, on: :collection
        end
      end

      resources :users do
        post :check_oib, on: :collection
        post :reset_password, on: :collection
      end
    end
  end

  devise_for :users, controllers: {registrations: 'api/v1/users', confirmations: 'api/v1/confirmations'}
  devise_for :admins, controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations', confirmations: 'admins/confirmations'}

  resources :notifications
  resources :offers
  resources :counties
  resources :cities
  resources :programme_types
  resources :purposes
  resources :company_sizes
  resources :companies
  resources :funding_programmes do
    put :delete_document, on: :collection
  end

  root 'funding_programmes#index'

end

fundings_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IZI Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">


  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand my-brand" href="#">IZI Admin</a>

    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse js--msr" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav ">
      </ul>


      <div class="nav navbar-nav navbar-left js--msr" >
        <a class="menu-slide-left js--msr-icon" id="menu-toggle" ><i class="ion-navicon-round"></i> </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Novi korisnik", new_admin_registration_path %></li>
        <li><%= link_to "Sign out", destroy_admin_session_path, :method => :delete %></li>

      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->

</nav>


<div id="wrapper" class="toggled">

  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li class="sidebar-brand">
        <a href="#" methods="get">

        </a>
      </li>
      <li class="<%= params[:controller] == 'funding_programmes' ? 'selected-menu' : '' %>">
        <%= link_to "Programi sufinanciranja", funding_programmes_path %>
      </li>
      <li class="<%= params[:controller] == 'company' ? 'selected-menu' : '' %>">
        <%= link_to "Registrirane kompanije", companies_path %>
      </li>
      <li class="<%= params[:controller] == 'offer' ? 'selected-menu' : '' %>">
        <%= link_to "Kreirane ponude", offers_path %>
      </li>
      <li class="<%= params[:controller] == 'purposes' ? 'selected-menu' : '' %>">
        <%= link_to "Slike", purposes_path %>
      </li>
      <li class="<%= params[:controller] == 'programme_types' ? 'selected-menu' : '' %>">
        <%= link_to "Tip programa", programme_types_path %>
      </li>
      <li class="<%= params[:controller] == 'company_sizes' ? 'selected-menu' : '' %>">
        <%= link_to "Pravni oblik", company_sizes_path %>
      </li>

    </ul>
  </div>
  <!-- /#sidebar-wrapper -->

  <!-- Page Content -->
  <div id="page-content-wrapper" style="padding-top: 70px;">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">

          <% if flash[:notice] %>
              <div class="alert alert-success" role="alert">
                <%= flash[:notice] %>
              </div>
          <% end %>

          <%= yield %>


        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    $(document).ready(function() {
        $('.js--msr-icon').click(function () {
            var icon = $('.js--msr-icon i');
            var nav = $('.js--msr a');
            if (icon.hasClass('ion-navicon-round')) {
                icon.addClass('ion-close-round');
                nav.addClass('menu-slide-right');
                icon.removeClass('ion-navicon-round');
                nav.removeClass('menu-slide-left');
            } else {
                icon.addClass('ion-navicon-round');
                nav.addClass('menu-slide-left');
                nav.removeClass('menu-slide-right');
                icon.removeClass('ion-close-round');
            }
        });
    });

    $(function() {
        $('.datepicker').datepicker();
    });
</script>

</body>
</html>

fundings_app/app/views/layouts/sign_in.erb
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login</title>

  <%= stylesheet_link_tag    'sign_in', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8"/>

</head>
<body class="align">

<div class="site__container">

  <div class="grid__container">

    <form action="" method="post" class="form form--login">

      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>

    </form>

  </div>

</div>
</body>
</html>