fundings_app/config/routes.rb
Rails.application.routes.draw do

  get 'offers/show'

  get 'offers/index'

  namespace :api do
  namespace :v1 do
      post 'favorites/create'
      post 'favorites/show'
      post 'favorites/destroy'
      post 'users/show'
      post 'users/create'
      post 'users/update'
      post 'users/destroy'
      post 'sessions/create'
      post 'sessions/destroy'
      post 'fundings/show'
      post 'fundings/index'
      post 'task/show'
      post 'task/create'
      post 'task/update'
      post 'offers/create'

      post 'notifications/set_flag'
      resource :filter, only: [:show, :create]
      resource :sms_confirmation, only: :create

      namespace :mobile do
        post 'ios_push_notifications/add_push_id_to_user'
        post 'ios_push_notifications/set_flag'
        post 'favorites/create'
        post 'favorites/show'
        post 'favorites/destroy'
        post 'users/show'
        post 'users/create'
        post 'users/update'
        post 'users/destroy'
        post 'android_sessions/create'
        post 'android_sessions/destroy'
        post 'ios_sessions/create'
        post 'ios_sessions/destroy'
        post 'fundings/show'
        post 'fundings/index'
        post 'android_push_notifications/set_flag'
        post 'android_push_notifications/add_push_id_to_user'

        resource :filter, only: [:show, :create]

        resources :users do
          post :check_oib, on: :collection
          post :reset_password, on: :collection
        end
      end

      resources :users do
        post :check_oib, on: :collection
        post :reset_password, on: :collection
      end
    end
  end

  devise_for :users, controllers: {registrations: 'api/v1/users', confirmations: 'api/v1/confirmations'}
  devise_for :admins, controllers: {sessions: 'admins/sessions', registrations: 'admins/registrations', confirmations: 'admins/confirmations'}

  resources :notifications
  resources :offers
  resources :counties
  resources :cities
  resources :programme_types
  resources :purposes
  resources :company_sizes
  resources :companies
  resources :funding_programmes do
    put :delete_document, on: :collection
  end

  root 'funding_programmes#index'

end

fundings_app/app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :county

  has_many :companies, :foreign_key => "city_id"
end

fundings_app/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:county_id, :name)
    end
end

fundings_app/app/helpers/cities_helper.rb
module CitiesHelper
end

fundings_app/app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :county_id %><br>
    <%= f.number_field :county_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fundings_app/app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

fundings_app/app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cities</h1>

<table>
  <thead>
    <tr>
      <th>County</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.county_id %></td>
        <td><%= city.name %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

fundings_app/app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

fundings_app/app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>County:</strong>
  <%= @city.county_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>